export const posts = [
  {
    slug: 'tailor-cv-job-description-netherlands',
    title: 'How to Tailor Your CV to a Job Description in the Netherlands',
    description: 'Dutch employers and ATS systems expect your CV to mirror the job description. Here\'s how to tailor your CV for the Dutch job market — step by step.',
    date: '2026-05-01',
    readTime: '5 min read',
    cover: {
      gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      emoji: '📝',
      alt: 'CV tailoring for the Netherlands job market',
    },
    content: [
      { type: 'p', text: 'The Netherlands job market is competitive. Whether you\'re applying to ASML in Eindhoven, Booking.com in Amsterdam, or a scale-up in Rotterdam — your CV needs to match the job description closely to make it past the first filter. In 2026, most applications never reach a recruiter\'s desk. They\'re filtered out by AI-powered ATS software before any human sees them.' },
      { type: 'p', text: 'Tailoring your CV to each job posting is the single most effective thing you can do to increase your interview rate. This guide explains exactly how.' },
      { type: 'h2', text: 'Why tailoring matters more than ever in 2026' },
      { type: 'p', text: 'Dutch companies have upgraded their hiring stacks significantly in 2025–2026. Platforms like Workday AI Recruiting, SAP SuccessFactors with AI screening, and Greenhouse\'s semantic matching layer are now standard at large Dutch employers including ING, Philips, Heineken, ASML, and Randstad. These systems no longer just match keywords — they evaluate semantic alignment between your CV and the job description.' },
      { type: 'p', text: 'A CV that scores below a set threshold gets filtered out automatically. The score is based on whether your CV contains the same terms and competency signals the employer used in the JD — in the right positions and with the right context.' },
      { type: 'h2', text: 'What tailoring actually means' },
      { type: 'p', text: 'Tailoring your CV does not mean inventing experience or exaggerating your background. It means presenting your real experience using the same language the employer uses.' },
      { type: 'p', text: 'For example: if the job description says "stakeholder management" and your CV says "worked with clients", you\'re describing the same skill — but the ATS won\'t recognise the match. This vocabulary gap is invisible to most candidates, and it\'s costing them interviews.' },
      { type: 'h2', text: 'Step-by-step: how to tailor your CV for a Dutch job posting' },
      { type: 'ol', items: [
        'Read the job description carefully and highlight the core requirements — skills, tools, methodologies, soft skills.',
        'Compare them against your CV. Note where your experience matches but uses different language.',
        'Rewrite each bullet point to lead with the JD\'s terminology. Replace "managed a team" with "led cross-functional teams" if that\'s what the JD says.',
        'Update your skills section to include the exact tools and terms from the JD — as long as you genuinely have them.',
        'Keep your CV to 1–2 pages. Dutch employers expect brevity and directness.',
      ]},
      { type: 'h2', text: 'The 2026 shift: AI vocabulary mapping' },
      { type: 'p', text: 'One of the biggest developments in 2026 ATS technology is vocabulary mapping — the ability to identify when a candidate uses a different term for the same concept than the employer does. For example, a CV that says "built ML models" may now be correctly matched to a JD that says "developed predictive analytics solutions", because the AI understands the semantic equivalence.' },
      { type: 'p', text: 'However, relying on the ATS to do this translation for you is a risk. The safest approach remains to use the JD\'s exact language where it accurately describes what you did. This closes the gap definitively, rather than leaving it to the scoring algorithm.' },
      { type: 'h2', text: 'The fastest way to do this' },
      { type: 'p', text: 'Manually comparing a CV against a job description takes 30–60 minutes per application. If you\'re applying to multiple roles — across different companies, sectors, or seniority levels — that adds up fast.' },
      { type: 'p', text: 'cv2jd automates the entire process. Paste your CV and the job description, and in seconds you get a fully rewritten CV that mirrors the JD\'s language, an ATS match score, and a vocabulary map showing exactly which terms were translated. Download it as a PDF, ready to submit.' },
      { type: 'cta' },
    ],
  },
  {
    slug: 'what-is-ats-how-to-pass-netherlands',
    title: 'What Is an ATS Score and How to Pass ATS Filters in the Netherlands',
    description: 'Most CVs in the Netherlands are screened by ATS software before a recruiter sees them. Here\'s how ATS scoring works in 2026 — and how to make sure your CV gets through.',
    date: '2026-05-01',
    readTime: '6 min read',
    cover: {
      gradient: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
      emoji: '🎯',
      alt: 'ATS scoring and filters in the Netherlands',
    },
    content: [
      { type: 'p', text: 'If you\'ve submitted dozens of applications and heard nothing back, your CV might not be making it past the first gate — an Applicant Tracking System (ATS). In 2026, these tools have become significantly more sophisticated, automatically screening and ranking applications before any recruiter reads them. Understanding how they work is the first step to beating them.' },
      { type: 'h2', text: 'What is an ATS?' },
      { type: 'p', text: 'An Applicant Tracking System is software used by employers to manage job applications at scale. It parses every CV submitted, extracts key information, and scores each candidate against the job description. Applications below a set score are filtered out.' },
      { type: 'p', text: 'ATS software is standard practice at large Dutch employers. Companies like ASML, ING, Shell Netherlands, Booking.com, and Randstad all route applications through ATS before a human reviews them. Smaller companies increasingly use it too, via platforms like LinkedIn Easy Apply, Recruitee, and Teamtailor — all of which added AI screening layers in 2025.' },
      { type: 'h2', text: 'How 2026 ATS systems score your CV' },
      { type: 'p', text: 'The scoring logic has evolved significantly from the keyword-matching engines of a few years ago. Modern ATS platforms use a combination of:' },
      { type: 'ul', items: [
        'Semantic keyword matching — understanding that "customer relations" and "client management" describe the same competency, but preferring the JD\'s exact phrasing.',
        'Job title alignment — comparing your previous titles to the role\'s expected career progression.',
        'Skills coverage — scoring how many of the required tools, methods, and competencies appear in your CV.',
        'Position weighting — bullets near the top of each role entry are scored more heavily than those further down.',
        'Formatting readability — can the ATS actually extract text from your CV? Tables, text boxes, images, and multi-column layouts still break parsing in most systems.',
      ]},
      { type: 'h2', text: 'Common reasons CVs fail ATS in the Netherlands' },
      { type: 'ul', items: [
        'Using Dutch job title conventions when applying for English-language roles (or vice versa).',
        'Describing skills with different words than the JD uses — "customer relations" vs "client management" will not match in older systems.',
        'Generic language like "responsible for" or "assisted with" — ATS systems prefer concrete, action-oriented text.',
        'Fancy PDF layouts with columns and tables that ATS software cannot parse correctly.',
        'Missing a skills section entirely — many ATS systems specifically scan this area for keyword density.',
        'Outdated software versions listed — listing "Excel 2016" when the JD says "Microsoft 365" signals a gap that doesn\'t exist.',
      ]},
      { type: 'h2', text: 'What changed in 2026: AI-assisted shortlisting' },
      { type: 'p', text: 'Beyond initial ATS screening, many Dutch employers now use a second AI layer for shortlisting. LinkedIn Recruiter\'s AI Hiring Assistant, Greenhouse\'s candidate scoring, and bespoke AI tools built on top of HR platforms now rank shortlisted candidates before a recruiter opens a single file. These systems compare your profile against the profiles of people who previously succeeded in similar roles at that company.' },
      { type: 'p', text: 'The practical implication: your most recent role and its top 2–3 bullets carry disproportionate weight. If those don\'t align with the JD\'s priorities, no amount of strong experience further down will compensate.' },
      { type: 'h2', text: 'How to check your ATS score before applying' },
      { type: 'p', text: 'The most reliable way is to compare your CV against the job description line by line — but that\'s time-consuming at scale. A faster approach is to use cv2jd.' },
      { type: 'p', text: 'Paste your CV and the job description into cv2jd and you\'ll get an ATS match score, a rewritten version that closes the keyword gaps, and a vocabulary map showing exactly where your language diverged from the employer\'s. The download produces a single-column, ATS-safe document that any parsing system can read correctly.' },
      { type: 'cta' },
    ],
  },
  {
    slug: 'cv-tips-netherlands-job-market',
    title: 'CV Tips for the Dutch Job Market: What Employers in the Netherlands Expect in 2026',
    description: 'Applying for jobs in the Netherlands? Dutch employers have specific expectations about CV format, length, and content. Get these right before you start tailoring.',
    date: '2026-05-01',
    readTime: '5 min read',
    cover: {
      gradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
      emoji: '💼',
      alt: 'CV tips for the Dutch job market in 2026',
    },
    content: [
      { type: 'p', text: 'The Dutch job market has its own conventions. Whether you\'re a local applicant or an expat competing for international roles in Amsterdam, Eindhoven, or Utrecht, understanding what Dutch employers expect from a CV gives you a structural advantage before you even start tailoring to specific roles.' },
      { type: 'h2', text: 'Dutch CV format basics' },
      { type: 'ul', items: [
        'Length: 1 page for under 5 years of experience, 2 pages maximum for senior roles. Dutch employers are direct and value conciseness.',
        'Language: Apply in the language of the job posting. English for international and tech roles, Dutch for local and public-sector positions.',
        'Photo: Traditionally included in the Netherlands, but increasingly optional at international companies. When in doubt, leave it out.',
        'Personal details: Name, city, phone, email, LinkedIn URL. Date of birth and marital status are not expected and are privacy-protected under Dutch GDPR implementation.',
        'No "Curriculum Vitae" header — Dutch recruiters know what a CV is.',
      ]},
      { type: 'h2', text: 'What Dutch employers prioritise in 2026' },
      { type: 'p', text: 'Dutch hiring culture is direct and results-oriented. Recruiters scan quickly and respond to specifics, not generalities.' },
      { type: 'ul', items: [
        'Concrete outcomes over job descriptions — numbers, scale, and impact matter. "Grew revenue by 40%" beats "responsible for sales growth".',
        'Most recent and relevant experience first — no need for a chronological career narrative that buries your best work.',
        'A short professional summary (3–5 sentences) that directly states who you are and what you bring to this specific role.',
        'A clear skills section — especially important for tech, data, and engineering roles where ATS keyword matching is heavy.',
        'Evidence of AI tool fluency — in 2026, many Dutch employers in tech, finance, and consulting now expect candidates to demonstrate how they work alongside AI tools in their day-to-day role.',
      ]},
      { type: 'h2', text: 'The Dutch job market in 2026: what\'s changed' },
      { type: 'p', text: 'Applications via LinkedIn, company portals, and recruitment agencies in the Netherlands have all shifted heavily toward AI-assisted screening. LinkedIn\'s AI Hiring Assistant — rolled out across the Netherlands in late 2025 — now pre-ranks candidates before a recruiter opens a file, weighing semantic alignment with the JD above keyword density alone.' },
      { type: 'p', text: 'The Amsterdam tech corridor, the Brainport Eindhoven ecosystem, and international companies operating out of the Netherlands all use ATS software as standard. ASML, Booking.com, IMEC, and major Dutch banks have all upgraded their ATS platforms to AI-enhanced versions in 2025–2026, making semantic CV matching the new baseline.' },
      { type: 'p', text: 'This means a well-formatted CV is no longer enough. Each application needs to mirror the language of the specific job description — what you call your skills needs to match what the employer calls them. In 2026, this matching happens at a semantic level, but using the JD\'s exact phrasing still outperforms relying on the algorithm to infer equivalence.' },
      { type: 'h2', text: 'New in 2026: the skills that are opening doors in the Netherlands' },
      { type: 'p', text: 'LinkedIn\'s 2026 Dutch Jobs Report identifies the fastest-growing skill requirements in Netherlands-based job postings:' },
      { type: 'ul', items: [
        'AI collaboration and prompt engineering — expected in tech, marketing, finance, and increasingly in operations roles.',
        'Data literacy — the ability to read, interpret, and present data-backed recommendations is now a baseline expectation at most knowledge-worker levels.',
        'Sustainability and ESG reporting — driven by EU Corporate Sustainability Reporting Directive (CSRD) requirements that took full effect in 2026.',
        'Cybersecurity awareness — with Dutch regulatory requirements tightening under NIS2, even non-technical roles are expected to demonstrate basic cybersecurity hygiene.',
      ]},
      { type: 'h2', text: 'How to tailor your CV for every Dutch application without spending an hour on each one' },
      { type: 'p', text: 'cv2jd is built for exactly this. Paste your CV and the job description — it rewrites your CV to match the role\'s language, gives you an ATS match score, and identifies the vocabulary gaps between what you said and what the employer is looking for. Takes less than a minute. Free, no sign-up.' },
      { type: 'cta' },
    ],
  },
]

export function getPostBySlug(slug) {
  return posts.find(p => p.slug === slug) || null
}
