import Head from 'next/head'
import Link from 'next/link'

const LAST_UPDATED = '28 April 2026'

const sections = [
  {
    title: '1. About cv2jd',
    content: `cv2jd is a free, AI-powered CV tailoring tool. It rewrites your CV to better match a job description, improving alignment with applicant tracking systems (ATS) and highlighting your most relevant experience. The service is provided free of charge with no subscription required.`,
  },
  {
    title: '2. Using the service',
    content: `You are welcome to use cv2jd for personal, non-commercial job seeking purposes. By using the service, you agree to these Terms.

You must not use cv2jd to:
- Generate CVs on behalf of others without their knowledge or consent
- Submit CVs containing false, fabricated, or misleading information about experience, qualifications, or identity
- Attempt to reverse-engineer, scrape, or abuse the service in ways that could harm other users or our infrastructure
- Use the service for any unlawful purpose`,
  },
  {
    title: '3. AI-generated content — important disclaimer',
    content: `The tailored CV produced by cv2jd is generated by an AI language model (Groq's Llama 3.3). While we instruct the AI to only reframe real experience — not invent it — AI systems can make mistakes.

**You are responsible for reviewing all AI output before submitting a CV to any employer.** We strongly recommend:
- Reading the tailored CV carefully before using it
- Verifying that every claim, achievement, and qualification is accurate
- Removing or correcting anything that does not reflect your real experience

cv2jd does not guarantee that the tailored CV will improve your chances of getting an interview or a job. ATS match scores are estimates only.`,
  },
  {
    title: '4. Your content',
    content: `When you paste your CV or a job description into cv2jd, you represent that you have the right to share that content.

For CVs: you are the author of your own CV and are free to share it.

For job descriptions: job postings are generally not copyright-protected in a way that prevents you from pasting them into a tool for personal use. However, you should not share confidential or unpublished job descriptions without authorisation.

We do not claim any ownership over your content. Your CV text is not stored on our servers and is not used to train AI models.`,
  },
  {
    title: '5. Intellectual property',
    content: `The cv2jd website, its design, branding, and software are owned by cv2jd. You may not copy, reproduce, or redistribute any part of the site without permission.

The AI output (your tailored CV) is yours to use freely for your job search.`,
  },
  {
    title: '6. No warranties',
    content: `cv2jd is provided "as is" and "as available", without warranty of any kind. We do not guarantee that the service will be uninterrupted, error-free, or produce any particular outcome in your job search.

To the fullest extent permitted by law, we disclaim all warranties, express or implied, including but not limited to implied warranties of merchantability and fitness for a particular purpose.`,
  },
  {
    title: '7. Limitation of liability',
    content: `To the maximum extent permitted by applicable law, cv2jd shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the service — including but not limited to loss of job opportunities, reliance on AI-generated content, or any errors in the tailored CV.

Our total liability for any claim relating to the service shall not exceed £100.`,
  },
  {
    title: '8. Third-party services',
    content: `cv2jd relies on third-party services including Groq (AI processing), Web3Forms (feedback delivery), PostHog (analytics), and Vercel (hosting). We are not responsible for the availability, accuracy, or conduct of these services. Your use of cv2jd is also subject to the terms of these third parties where applicable.`,
  },
  {
    title: '9. Changes to the service',
    content: `We may change, suspend, or discontinue any part of cv2jd at any time without notice. We may also update these Terms. Continued use of the service after changes are posted constitutes acceptance of the updated Terms. The "Last updated" date at the top of this page will reflect any changes.`,
  },
  {
    title: '10. Governing law',
    content: `These Terms are governed by the laws of England and Wales. Any disputes arising from these Terms or your use of cv2jd shall be subject to the exclusive jurisdiction of the courts of England and Wales.`,
  },
  {
    title: '11. Contact',
    content: `If you have any questions about these Terms, please contact us using the feedback form on our Pricing page.`,
  },
]

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service — cv2jd</title>
        <meta name="description" content="Terms of Service for cv2jd — the free AI-powered CV tailoring tool." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" type="image/png" />
      </Head>

      {/* NAV */}
      <nav style={{
        position: 'fixed', top: 0, width: '100%', zIndex: 1000,
        background: 'rgba(255,255,255,0.92)', backdropFilter: 'blur(12px)',
        borderBottom: '1px solid rgba(0,0,0,0.08)',
      }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 2rem', height: 68, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link href="/" style={{ display: 'flex', alignItems: 'center', textDecoration: 'none' }}>
            <img src="/logo.png" alt="cv2jd" style={{ height: 96, width: 'auto' }} />
          </Link>
          <Link href="/tailor" style={{
            background: 'linear-gradient(135deg, #667eea, #764ba2)',
            color: 'white', padding: '10px 24px', borderRadius: 50,
            fontSize: 15, fontWeight: 600, textDecoration: 'none',
          }}>
            Try it free →
          </Link>
        </div>
      </nav>

      {/* HERO STRIP */}
      <div style={{
        background: 'linear-gradient(135deg, #667eea, #764ba2)',
        padding: '96px 2rem 48px',
        textAlign: 'center',
        color: 'white',
      }}>
        <div style={{ fontSize: 40, marginBottom: 12 }}>📋</div>
        <h1 style={{ fontSize: 'clamp(2rem, 4vw, 2.8rem)', fontWeight: 900, marginBottom: 12, letterSpacing: '-0.5px' }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 16, opacity: 0.85, marginBottom: 8 }}>
          Last updated: {LAST_UPDATED}
        </p>
        <p style={{ fontSize: 15, opacity: 0.75, maxWidth: 560, margin: '0 auto' }}>
          By using cv2jd, you agree to these terms. They&apos;re written in plain English —
          please read them before submitting any CV to an employer.
        </p>
      </div>

      {/* CONTENT */}
      <main style={{ background: '#fafafa', padding: '48px 2rem 80px' }}>
        <div style={{ maxWidth: 760, margin: '0 auto' }}>

          {/* Key points summary */}
          <div style={{
            background: 'white', borderRadius: 16, padding: '24px 32px',
            border: '1px solid #e8e8f0', marginBottom: 24,
            boxShadow: '0 2px 8px rgba(0,0,0,0.03)',
          }}>
            <h2 style={{ fontSize: 16, fontWeight: 800, color: '#764ba2', marginTop: 0, marginBottom: 16, textTransform: 'uppercase', letterSpacing: 0.5 }}>
              ⚡ Key points
            </h2>
            <ul style={{ margin: 0, paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 10 }}>
              {[
                'The service is free. There is no subscription or credit card required.',
                'Always review AI-generated output — you are responsible for the accuracy of your CV.',
                'Do not use cv2jd to fabricate experience or mislead employers.',
                'We do not store your CV. See our Privacy Policy for full details.',
                'The service is provided as-is. We make no guarantees about job search outcomes.',
              ].map((point, i) => (
                <li key={i} style={{ fontSize: 15, color: '#444', lineHeight: 1.6 }}>
                  {point}
                </li>
              ))}
            </ul>
          </div>

          {/* Sections */}
          {sections.map((s) => (
            <div key={s.title} style={{
              background: 'white', borderRadius: 16, padding: '28px 32px',
              border: '1px solid #e8e8f0', marginBottom: 16,
              boxShadow: '0 2px 8px rgba(0,0,0,0.03)',
            }}>
              <h2 style={{ fontSize: 18, fontWeight: 800, color: '#1a1a2e', marginBottom: 16, marginTop: 0 }}>
                {s.title}
              </h2>
              <div style={{ fontSize: 15, color: '#444', lineHeight: 1.75 }}>
                {s.content.split('\n\n').map((para, i) => {
                  if (para.startsWith('**') && para.includes('**')) {
                    return (
                      <p key={i} style={{ margin: '0 0 14px' }}>
                        {para.split(/(\*\*.*?\*\*)/).map((chunk, j) =>
                          chunk.startsWith('**') && chunk.endsWith('**')
                            ? <strong key={j}>{chunk.replace(/\*\*/g, '')}</strong>
                            : chunk
                        )}
                      </p>
                    )
                  }
                  if (para.startsWith('- ')) {
                    return (
                      <ul key={i} style={{ paddingLeft: 20, margin: '0 0 14px' }}>
                        {para.split('\n').map((line, j) => (
                          <li key={j} style={{ marginBottom: 6 }}>{line.replace(/^- /, '')}</li>
                        ))}
                      </ul>
                    )
                  }
                  return <p key={i} style={{ margin: '0 0 14px' }}>{para}</p>
                })}
              </div>
            </div>
          ))}

          {/* Privacy link */}
          <div style={{
            background: 'linear-gradient(135deg, #667eea15, #764ba220)',
            borderRadius: 16, padding: '28px 32px', marginTop: 32,
            border: '1px solid #764ba230', textAlign: 'center',
          }}>
            <p style={{ fontSize: 15, color: '#555', margin: '0 0 16px' }}>
              For information on how we handle your data, see our Privacy Policy.
            </p>
            <Link href="/privacy" style={{
              background: 'linear-gradient(135deg, #667eea, #764ba2)',
              color: 'white', padding: '12px 28px', borderRadius: 50,
              fontSize: 15, fontWeight: 700, textDecoration: 'none', display: 'inline-block',
            }}>
              Read Privacy Policy →
            </Link>
          </div>
        </div>
      </main>

      {/* FOOTER */}
      <footer style={{ background: '#0f0f1a', color: '#aaa', padding: '40px 2rem' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center' }}>
            <img src="/logo.png" alt="cv2jd" style={{ height: 80, width: 'auto', borderRadius: 6 }} />
          </div>
          <div style={{ fontSize: 14 }}>© 2026 cv2jd. AI-powered CV tailoring.</div>
          <div style={{ display: 'flex', gap: 20, fontSize: 14 }}>
            <Link href="/privacy" style={{ color: '#aaa' }}
              onMouseEnter={e => e.target.style.color = 'white'}
              onMouseLeave={e => e.target.style.color = '#aaa'}>Privacy</Link>
            <Link href="/terms" style={{ color: '#764ba2', fontWeight: 600 }}>Terms</Link>
            <Link href="/pricing" style={{ color: '#aaa' }}
              onMouseEnter={e => e.target.style.color = 'white'}
              onMouseLeave={e => e.target.style.color = '#aaa'}>Contact</Link>
          </div>
        </div>
      </footer>
    </>
  )
}
